/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PacoteJanelas_GUI;

import javax.swing.ImageIcon;

/**
 *
 * @author Laercio-pc
 */
public class JFRadioButtom extends javax.swing.JFrame {

    /**
     * Creates new form JFRadioButtom
     */
    public JFRadioButtom() {
        initComponents();

    }

    ImageIcon img;

    public void selecionaImagemJButton() {

        ImageIcon img;

        if (rdbPorco.isSelected()) {
            img = new ImageIcon(getClass().getResource("pig.png"));
            img.setImage(img.getImage().getScaledInstance(lblImagem.getWidth(), lblImagem.getHeight(), 1));
            lblImagem.setIcon(img);
        }
        if (rdbCoelho.isSelected()) {
            img = new ImageIcon(getClass().getResource("coelho.png"));
            img.setImage(img.getImage().getScaledInstance(lblImagem.getWidth(), lblImagem.getHeight(), 1));
            lblImagem.setIcon(img);
        }
        if (rdbGato.isSelected()) {
            img = new ImageIcon(getClass().getResource("cat.png"));
            img.setImage(img.getImage().getScaledInstance(lblImagem.getWidth(), lblImagem.getHeight(), 1));
            lblImagem.setIcon(img);
        }
        if (rdbPassaro.isSelected()) {
            img = new ImageIcon(getClass().getResource("bird.png"));
            img.setImage(img.getImage().getScaledInstance(lblImagem.getWidth(), lblImagem.getHeight(), 1));
            lblImagem.setIcon(img);
        }
        if (rdbCachorro.isSelected()) {
            img = new ImageIcon(getClass().getResource("dog.png"));
            img.setImage(img.getImage().getScaledInstance(lblImagem.getWidth(), lblImagem.getHeight(), 1));
            lblImagem.setIcon(img);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgAnimais = new javax.swing.ButtonGroup();
        rdbPorco = new javax.swing.JRadioButton();
        rdbPassaro = new javax.swing.JRadioButton();
        rdbCoelho = new javax.swing.JRadioButton();
        rdbCachorro = new javax.swing.JRadioButton();
        lblImagem = new javax.swing.JLabel();
        rdbGato = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btgAnimais.add(rdbPorco);
        rdbPorco.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        rdbPorco.setText("Porco");
        rdbPorco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbPorcoActionPerformed(evt);
            }
        });

        btgAnimais.add(rdbPassaro);
        rdbPassaro.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        rdbPassaro.setText("Pássaro");
        rdbPassaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbPassaroActionPerformed(evt);
            }
        });

        btgAnimais.add(rdbCoelho);
        rdbCoelho.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        rdbCoelho.setText("Coelho");
        rdbCoelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbCoelhoActionPerformed(evt);
            }
        });

        btgAnimais.add(rdbCachorro);
        rdbCachorro.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        rdbCachorro.setText("Cachorro");
        rdbCachorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbCachorroActionPerformed(evt);
            }
        });

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteJanelas_GUI/cat.png"))); // NOI18N
        lblImagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btgAnimais.add(rdbGato);
        rdbGato.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        rdbGato.setText("Gato");
        rdbGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbGatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rdbCachorro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbGato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbPorco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbPassaro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbCoelho, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(rdbPorco, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbPassaro, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbCoelho, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbGato, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbCachorro, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rdbPorcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbPorcoActionPerformed
        // TODO add your handling code here:
        selecionaImagemJButton();
    }//GEN-LAST:event_rdbPorcoActionPerformed

    private void rdbPassaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbPassaroActionPerformed
        // TODO add your handling code here:
        selecionaImagemJButton();
    }//GEN-LAST:event_rdbPassaroActionPerformed

    private void rdbCoelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbCoelhoActionPerformed
        // TODO add your handling code here:
        selecionaImagemJButton();
    }//GEN-LAST:event_rdbCoelhoActionPerformed

    private void rdbGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbGatoActionPerformed
        // TODO add your handling code here:
        selecionaImagemJButton();
    }//GEN-LAST:event_rdbGatoActionPerformed

    private void rdbCachorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbCachorroActionPerformed
        // TODO add your handling code here:
        selecionaImagemJButton();
    }//GEN-LAST:event_rdbCachorroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFRadioButtom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFRadioButtom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFRadioButtom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFRadioButtom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFRadioButtom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgAnimais;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JRadioButton rdbCachorro;
    private javax.swing.JRadioButton rdbCoelho;
    private javax.swing.JRadioButton rdbGato;
    private javax.swing.JRadioButton rdbPassaro;
    private javax.swing.JRadioButton rdbPorco;
    // End of variables declaration//GEN-END:variables
}
